version: 2.1

jobs:
  build:
    docker:
      - image: lomography/wolfe:1.1
        environment:
          RAILS_ENV: test
          RUBY_VERSION: 3.1.1
          BUNDLER_VERSION: 2.1.4
    resource_class: small
    steps:
      - checkout
      - run:
          name: Run rails tests
          command: bundle exec rake


