version: 2.1

jobs:
  build:
    docker:
      - image: lomographydev/wolfe:1.0
        auth:
          username: lomographydev
          password: $DOCKERHUB_ACCESS_TOKEN
        environment:
          RAILS_ENV: test
          RUBY_VERSION: 3.1.1
          BUNDLER_VERSION: 2.1.4
    resource_class: small
    steps:
      - checkout
      - run:
          name: Run rails tests
          command: bundle exec rake


